[nwp] New spack env for balfrin and add realloc in configure
See merge request icon/icon-nwp!950

- new option for configure : enable-realloc-buf , default no. 
  This is an optimization in the communication mostly beneficial for GPUs.
- only compiles variants that are needed for MCH production on Balfrin
  - using new spack v0.18.1.9
  - set variant gpu=openacc+cuda this sets realloc_com_buffer and dim swap in configure
  - set variant +mpi-gpu this sets G2G in configure
  - set variant +enable-realloc-buf 
  - emvordao deactivaed for mixed precision on balfrin

Approved-by: Sergey Kosukhin <sergey.kosukhin@mpimet.mpg.de>
Merged-by: Daniel Reinert <daniel.reinert@dwd.de>

diff --git a/config/cscs/spack_install b/config/cscs/spack_install
--- a/config/cscs/spack_install
+++ b/config/cscs/spack_install
@@ -27,3 +27,28 @@ spack install -v
 spack env activate -p $ICON_DIR/config/cscs/spack/$SPACK_VERSION/$VARIANT
 # store ECCODES_DEFINITION_PATH in setting, should be later replaced with spack env activate --sh
 echo "export ECCODES_DEFINITION_PATH=${ECCODES_DEFINITION_PATH}" >> $ICON_DIR/setting
+
+# Workaround for Balfrin to set cuda library in LD_LIBRARY_PATH
+# This relies on the spack env activate
+machine="$( ./spack-c2sm/src/machine.sh )"
+if [[ $machine == "balfrin" && "$VARIANT" == *"gpu"* ]]; then
+ 
+  # Extract path to upstream used by spack, this contains also the modules
+  spack_upstream=`spack config get upstreams |grep install_tree`
+  spack_upstream=${spack_upstream#*install_tree:}
+  if [ ! -d $spack_upstream/modules ]; then
+    echo "Error: $spack_upstream/modules is not a directory"
+    exit 1
+  fi
+  module use $spack_upstream/modules
+  cuda_lib_path=`module show cuda 2>&1 |grep LD_LIBRARY_PATH`
+
+  cuda_lib_path=/${cuda_lib_path#*/}
+  if [ ! -d $cuda_lib_path ]; then
+    echo "Error: $cuda_path_lib does not exists"
+    exit 1
+  fi
+  echo "Prepend LD_LIBRARY_PATH with $cuda_lib_path in run setting"
+  echo "export LD_LIBRARY_PATH=$cuda_lib_path\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" >> $ICON_DIR/setting
+  echo "echo Info: cuda path is set in LD_LIBRARY_PATH=\$LD_LIBRARY_PATH" >> $ICON_DIR/setting
+fi
